"""add is_public to albums

Revision ID: 1f2a3b4c5d67
Revises: a40fbae3db73
Create Date: 2025-11-18
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1f2a3b4c5d67'
down_revision: Union[str, None] = 'a40fbae3db73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'is_public')
    # ### end Alembic commands ###
